"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:51:35.187624+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql.functions import distinct
import json
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_date, input_file_name, lit, max, when
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType
from pyspark.sql.functions import broadcast
from pyspark.sql.window import Window
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Define schema for bronze layer
    bronze_schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("customer_id", StringType(), True),
        StructField("transaction_amount", StringType(), True),
        StructField("transaction_timestamp", StringType(), True),
        StructField("transaction_status", StringType(), True)
    ])

    # Read raw transaction data
    bronze_df = (spark.readStream
                .format("csv")
                 .option("header", "true")
                .schema(bronze_schema)
                 .load(input_path)
                 .withColumn("ingestion_timestamp", current_date())
                .withColumn("source_file", input_file_name())
                 .withColumn("pipeline_run_id", lit(run_id))
                .withColumn("load_date", col("transaction_timestamp").cast(DateType())))

    # Write to Delta Lake partitioned by load_date
    (bronze_df.writeStream
    .format("parquet")
    .partitionBy("load_date")
    .outputMode("append")
    .option("path", output_path)
    .start()
    .awaitTermination())

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze layer data with partition pruning
    bronze_df = (spark.read.format("parquet")
                 .load(bronze_path)
                .where(col("load_date") >= (current_date() - 30))
                .cache())

    # Define schema for Silver layer
    silver_schema = StructType([
        StructField("transaction_id", StringType(), False),
        StructField("customer_id", StringType(), False),
        StructField("transaction_amount", FloatType(), False),
        StructField("transaction_timestamp", DateType(), False),
        StructField("transaction_status", StringType(), False),
        StructField("ingestion_timestamp", DateType(), False),
        StructField("source_file", StringType(), False),
        StructField("pipeline_run_id", StringType(), False),
        StructField("load_date", DateType(), False)
    ])

    # Cast columns to correct types
    silver_df = (bronze_df.select([col(c).cast(silver_schema[c].dataType()) for c in silver_schema.fieldNames()])
                .filter(col("transaction_amount").cast(FloatType()) > 0)
                .filter(col("transaction_id").isNotNull()))

    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    silver_df = (silver_df.withColumn("rank", 
                                      when(col("transaction_id").isNotNull(), 
                                           max("ingestion_timestamp").over(Window.partitionBy("transaction_id")))
                                     )
                .filter(col("rank") == col("ingestion_timestamp"))
                 .drop("rank"))

    # Read merchants data and broadcast hint
    merchants_df = (spark.read.format("parquet").load(merchants_path).hint("broadcast"))

    # Join with merchants and add quality_flag column
    silver_df = (silver_df.join(merchants_df, silver_df.customer_id == merchants_df.customer_id, "left")
                 .withColumn("quality_flag", when(col("merchants.customer_id").isNotNull(), "CLEAN").otherwise("UNMATCHED")))

    # Write to Silver layer partitioned by transaction_date
    (silver_df.write
    .format("parquet")
    .partitionBy("transaction_timestamp")
    .mode("overwrite")
     .save(output_path))

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Customer Segmentation Pipeline")
             .getOrCreate())

    # Define paths and run parameters
    input_path = os.getenv("INPUT_PATH")
    bronze_output_path = os.getenv("BRONZE_OUTPUT_PATH")
    merchants_path = os.getenv("MERCHANTS_PATH")
    silver_output_path = os.getenv("SILVER_OUTPUT_PATH")
    run_date = os.getenv("RUN_date")
    run_id = os.getenv("RUN_ID")

    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_output_path, run_date, run_id)

    # Transform to Silver layer
    transform_silver(spark, bronze_output_path, merchants_path, silver_output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, min, expr, broadcast, when, coalesce, lit
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType, DateType
from pyspark.sql.window import Window


def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Initialize metadata dictionary
    run_metadata = {}

    # Build merchant performance
    merchant_performance_path = f"{gold_output_dir}/merchant_performance"
    build_merchant_performance(spark, silver_path, merchant_performance_path, run_date)
    run_metadata['merchant_performance'] = merchant_performance_path

    # Build customer LTV
    customer_ltv_path = f"{gold_output_dir}/customer_ltv"
    build_customer_ltv(spark, silver_path, customer_ltv_path)
    run_metadata['customer_ltv'] = customer_ltv_path

    # Build daily summary
    daily_summary_path = f"{gold_output_dir}/daily_summary"
    build_daily_summary(spark, silver_path, daily_summary_path, run_date)
    run_metadata['daily_summary'] = daily_summary_path

    # Write run metadata to JSON
    run_metadata_json_path = f"{gold_output_dir}/run_metadata.json"
    spark.read.json([json.dumps(run_metadata)]).write.mode('overwrite').json(run_metadata_json_path)

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read silver transactions
    silver_transactions = spark.read.parquet(silver_path).filter(col("transaction_status") == "COMPLETED")

    # Calculate metrics
    merchant_performance = silver_transactions.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("transaction_status") == "FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write output
    merchant_performance.write.partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read silver transactions
    silver_transactions = spark.read.parquet(silver_path).filter(col("transaction_status") == "COMPLETED")

    # Calculate metrics
    customer_ltv = silver_transactions.groupBy("customer_id") \
        .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            max("transaction_timestamp").alias("first_txn_date"),
            min("transaction_timestamp").alias("last_txn_date"),
            coalesce(expr("mode(preferred_payment_method)"), lit(None)).alias("preferred_payment_method")
        )

    # Write output
    customer_ltv.write.parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read silver transactions
    silver_transactions = spark.read.parquet(silver_path)

    # Calculate metrics
    daily_summary = silver_transactions.groupBy("date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            count(when(col("transaction_status") == "COMPLETED")).alias("unique_txns"),
            count(distinct("customer_id")).alias("unique_customers"),
            count(distinct("merchant_id")).alias("unique_merchants"),
            (count(when(col("transaction_status") == "FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write output
    daily_summary.write.partitionBy("date").parquet(output_path)

if __name__ == "__main__":
    spark = SparkSession.builder.appName("Gold Pipeline").getOrCreate()
    silver_path = os.getenv("SILVER_OUTPUT_PATH")
    gold_output_dir = os.getenv("GOLD_OUTPUT_PATH")
    run_date = os.getenv("RUN_DATE")
    run_gold(spark, silver_path, gold_output_dir, run_date)

