-- models/marts/mart_merchant_kpis.sql

WITH filtered_transactions AS (
    SELECT
        transaction_id,
        amount,
        status,
        merchant_id,
        customer_id,
        transaction_date,
        payment_method
    FROM {{ ref('stg_fact_transactions') }}
    WHERE status IN ('COMPLETED', 'FAILED')
),

merchant_transactions AS (
    SELECT
        ft.merchant_id,
        ft.amount,
        ft.status,
        ft.customer_id,
        ft.transaction_date,
        COUNT(*) OVER (PARTITION BY ft.merchant_id) AS total_transactions,
        COUNT(CASE WHEN ft.status = 'FAILED' THEN 1 END) OVER (PARTITION BY ft.merchant_id) AS failed_count,
        COUNT(DISTINCT ft.customer_id) OVER (PARTITION BY ft.merchant_id) AS unique_customers
    FROM filtered_transactions ft
),

aggregated_metrics AS (
    SELECT
        mt.merchant_id,
        SUM(mt.amount) AS total_revenue,
        mt.total_transactions,
        mt.failed_count,
        (mt.failed_count::DECIMAL / mt.total_transactions) * 100 AS failure_rate_pct,
        AVG(mt.amount) AS avg_transaction_value,
        mt.unique_customers
    FROM merchant_transactions mt
    GROUP BY mt.merchant_id, mt.total_transactions, mt.failed_count, mt.unique_customers
)

SELECT
    am.merchant_id,
    dm.merchant_name,
    am.total_revenue,
    am.total_transactions,
    am.failed_count,
    am.failure_rate_pct,
    am.avg_transaction_value,
    am.unique_customers
FROM aggregated_metrics am
JOIN {{ ref('dim_merchant') }} dm
    ON am.merchant_id = dm.merchant_id
```

```yaml
# models/marts/schema.yml

version: 2

models:
  - name: mart_merchant_kpis
    description: "Aggregated merchant KPIs including total revenue, total transactions, failed count, failure rate, average transaction value, and unique customers."
    columns:
      - name: merchant_id
        description: "Unique identifier for the merchant."
        tests:
          - not_null
          - relationships:
              to: ref('dim_merchant')
              field: merchant_id
      - name: merchant_name
        description: "Name of the merchant."
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated by the merchant from completed transactions."
        tests:
          - not_null
      - name: total_transactions
        description: "Total number of transactions for the merchant."
        tests:
          - not_null
      - name: failed_count
        description: "Number of failed transactions for the merchant."
        tests:
          - not_null
      - name: failure_rate_pct
        description: "Failure rate percentage for the merchant's transactions."
        tests:
          - not_null
      - name: avg_transaction_value
        description: "Average transaction value for the merchant."
        tests:
          - not_null
      - name: unique_customers
        description: "Number of unique customers who made transactions with the merchant."
        tests:
          - not_null
